export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:8080/api/v1',
  usersEndpointPath: '/users',
  adminsEndpointPath: '/admins',
  teachersPath: '/teachers',
  signInPath: '/sign-in',
  adminSignUpPath: '/sign-up',
  resetPasswordPath: '/reset-password',
  academyEndpointPath: '/academies',
  academicPeriodEndpointPath: "/academic-periods",
  studentsEndpointPath: "/students",
  enrollmentEndpointPath: "/enrollments",
  //invoicesEndpointPath: "/invoices",
  paymentsEndpointPath: "/payments",
  financialTransactionsEndpointPath: "/financial-transactions",
  coursesEndpointPath: '/courses',
  classroomsEndpointPath: '/classrooms',
  weeklyScheduleEndpointPath: '/weekly-schedules',
  attendancesEndpointPath: '/attendance-record',
  classSessionsEndpointPath: '/class-sessions',
  attendanceReportEndpointPath: '/class-sessions/report',
  payEndpointPath: '/payments',
  intentEndpointPath: '/create-intent',
};
