export const environment = {
  production: true,
  apiBaseUrl: 'http://localhost:8080/api/v1',
  usersEndpointPath: '/users',
  adminsEndpointPath: '/admins',
  teachersPath: '/teachers',
  signInPath: '/sign-in',
  adminSignUpPath: '/sign-up',
  resetPasswordPath: '/reset-password',
  academyEndpointPath: '/academies',
  academicPeriodEndpointPath: "/academic-periods",
  studentsEndpointPath: "/students2",
  enrollmentEndpointPath: "/enrollments",
  invoicesEndpointPath: "/invoices",
  paymentsEndpointPath: "/payments",
  financialTransactionsEndpointPath: "/financialTransactions",
  classSessionsEndpointPath: "/class-sessions",
  coursesEndpointPath: '/courses',
  classroomsEndpointPath: '/classrooms',
  weeklyScheduleEndpointPath: '/weekly-schedules',
  attendancesEndpointPath: '/attendance-record',
  payEndpointPath: '/payments',
  intentEndpointPath: '/create-intent',
};
